name: KitEngine
version: 1.4
description: An open sourced kit plugin
author: Mallis
main: com.DisabledMallis.KitEngine.Main
api-version: 1.14
softdepend: [Vault]
commands:
  savekit:
    usage: /savekit
    permission: kit.save
    description: Save a kit
  kit:
    usage: /kit <name>
    permission: kit.use
    description: Acquire a kit with the specified name
  debug:
    usage: /kit <name>
    description: KitEngine debuggin command, please ignore.
  kits:
    usage: /kits
    permission: kit.save
    description: Access to /kits, the kits gui.
  editkitgui:
    usage: /editkitsgui
    description: Edit the /kits gui
permissions:
  kit.*:
    description: gives access to all kit commands
    default: op
    children:
      kit.save: true
      kit.use: true
      kits.use: true
      kit.use.*: true
  kits.use:
    description: gives access to the '/kits' command
    default: true
  kit.use:
    description: gives access to the '/kit' command
    default: true
  kit.save:
    description: gives access to the '/savekit' command
    default: op
  kit.use.*:
    description: permission for all kits
    default: true
  kit.editgui:
    description: permission to edit the /kits gui
    default: op
  